# ============================================================
# FILE: .\backend\src\services\chart_generator.py
# ============================================================

import os
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import pandas as pd

from datetime import datetime
from src.core.config import Config
from src.core.logger import get_logger


class ChartGenerator:
    """Generates professional QA charts from clean, LLM-parsed JSON data."""

    COLORS = {
        "passed": "#4CAF50",
        "failed": "#F44336",
        "skipped": "#FF9800",
        "blocked": "#9E9E9E",
        "primary": "#e3000f",
        "secondary": "#2d2d2d",
        "background": "#f5f6f8",
        "grid": "#e0e0e0",
    }

    def __init__(self):
        self.logger = get_logger(self.__class__.__name__)
        self.output_dir = Config.OUTPUT_CHARTS_PATH
        os.makedirs(self.output_dir, exist_ok=True)

    def _apply_style(self, ax, title: str):
        """Applies consistent professional styling to a chart axis."""
        ax.set_title(
            title,
            fontsize=13,
            fontweight="bold",
            color=self.COLORS["secondary"],
            pad=12,
        )
        ax.set_facecolor("#ffffff")
        ax.figure.set_facecolor(self.COLORS["background"])
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["left"].set_color(self.COLORS["grid"])
        ax.spines["bottom"].set_color(self.COLORS["grid"])
        ax.tick_params(colors=self.COLORS["secondary"], labelsize=9)
        ax.grid(axis="y", linestyle="--", alpha=0.4, color=self.COLORS["grid"])

    def _save_chart(self, fig, name: str, project_name: str) -> str:
        """Saves a figure to disk and returns the file path."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        clean_project = project_name.replace(" ", "_")
        filename = f"{clean_project}_{name}_{timestamp}.png"
        filepath = os.path.join(self.output_dir, filename)
        fig.savefig(
            filepath, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor()
        )
        plt.close(fig)
        self.logger.info(f"Chart saved: {filepath}")
        return filepath

    def generate_all_charts(
        self, chart_data: dict, project_name: str, lang: str = "pl"
    ) -> list[str]:
        """
        Analyzes clean test data generated by LLM and generates all applicable charts.

        Args:
            chart_data: Dict with standardized 'tests' and 'bugs' arrays from LLM.
            project_name: Project name for file naming.
            lang: Language for chart labels.

        Returns:
            List of file paths to generated chart images.
        """
        chart_paths = []

        # Tworzymy DataFrame bezpośrednio z czystego JSONa
        tests_data = chart_data.get("tests", [])
        bugs_data = chart_data.get("bugs", [])

        df_tests = pd.DataFrame(tests_data)
        df_bugs = pd.DataFrame(bugs_data)

        # 1. Wykres kołowy wyników
        if not df_tests.empty and "status" in df_tests.columns:
            path = self._chart_test_results_donut(df_tests, project_name, lang)
            if path:
                chart_paths.append(path)

            # 2. Wykres słupkowy wg komponentów (tylko jeśli mamy komponenty)
            if "component" in df_tests.columns:
                path = self._chart_status_by_component(df_tests, project_name, lang)
                if path:
                    chart_paths.append(path)

        # 3. Wykres wagi defektów
        if not df_bugs.empty and "severity" in df_bugs.columns:
            path = self._chart_bug_severity(df_bugs, project_name, lang)
            if path:
                chart_paths.append(path)

        return chart_paths

    def _chart_test_results_donut(
        self, df: pd.DataFrame, project_name: str, lang: str
    ) -> str | None:
        """Generates a donut chart showing pass/fail/skip distribution."""
        # LLM zawsze zwraca znormalizowane statusy z dużej litery (Passed, Failed)
        counts = df["status"].value_counts()
        if counts.empty:
            return None

        color_map = {
            "Passed": self.COLORS["passed"],
            "Failed": self.COLORS["failed"],
            "Skipped": self.COLORS["skipped"],
            "Blocked": self.COLORS["blocked"],
        }
        colors = [color_map.get(s, "#607D8B") for s in counts.index]
        title = (
            "Rozkład wyników testów" if lang == "pl" else "Test Results Distribution"
        )

        fig, ax = plt.subplots(figsize=(7, 5))
        fig.set_facecolor(self.COLORS["background"])
        wedges, texts, autotexts = ax.pie(
            counts.values,
            labels=counts.index,
            autopct=lambda pct: f"{pct:.1f}%\n({int(round(pct / 100 * sum(counts.values)))})",
            colors=colors,
            startangle=90,
            pctdistance=0.78,
            wedgeprops=dict(width=0.45, edgecolor="white", linewidth=2),
        )
        for t in autotexts:
            t.set_fontsize(9)
            t.set_fontweight("bold")
        for t in texts:
            t.set_fontsize(10)

        total = sum(counts.values)
        ax.text(
            0,
            0,
            f"{total}",
            ha="center",
            va="center",
            fontsize=22,
            fontweight="bold",
            color=self.COLORS["secondary"],
        )
        label = "testów" if lang == "pl" else "tests"
        ax.text(
            0,
            -0.12,
            label,
            ha="center",
            va="center",
            fontsize=10,
            color=self.COLORS["secondary"],
        )

        ax.set_title(
            title,
            fontsize=13,
            fontweight="bold",
            color=self.COLORS["secondary"],
            pad=16,
        )

        return self._save_chart(fig, "results_donut", project_name)

    def _chart_status_by_component(
        self, df: pd.DataFrame, project_name: str, lang: str
    ) -> str | None:
        """Generates a stacked bar chart showing test status per component/module."""
        pivot = df.pivot_table(
            index="component", columns="status", aggfunc="size", fill_value=0
        )

        title = (
            "Wyniki testów wg komponentu"
            if lang == "pl"
            else "Test Results by Component"
        )
        color_map = {
            "Passed": self.COLORS["passed"],
            "Failed": self.COLORS["failed"],
            "Skipped": self.COLORS["skipped"],
            "Blocked": self.COLORS["blocked"],
        }
        colors = [color_map.get(c, "#607D8B") for c in pivot.columns]

        fig, ax = plt.subplots(figsize=(9, 5))
        pivot.plot(
            kind="bar",
            stacked=True,
            ax=ax,
            color=colors,
            edgecolor="white",
            linewidth=0.5,
        )
        self._apply_style(ax, title)
        ax.legend(loc="upper right", fontsize=9, framealpha=0.9)
        ax.set_xlabel("")
        ylabel = "Liczba testów" if lang == "pl" else "Test Count"
        ax.set_ylabel(ylabel, fontsize=10)
        ax.yaxis.set_major_locator(mticker.MaxNLocator(integer=True))
        plt.xticks(rotation=30, ha="right")
        fig.tight_layout()

        return self._save_chart(fig, "status_by_component", project_name)

    def _chart_bug_severity(
        self, df: pd.DataFrame, project_name: str, lang: str
    ) -> str | None:
        """Generates a horizontal bar chart of bug counts by severity."""
        counts = df["severity"].value_counts().sort_values(ascending=True)
        if counts.empty:
            return None

        title = (
            "Błędy wg poziomu ważności" if lang == "pl" else "Bugs by Severity Level"
        )

        severity_colors = []
        for label in counts.index:
            l_val = str(label).lower()
            if l_val in ("critical", "krytyczny", "blocker"):
                severity_colors.append("#B71C1C")
            elif l_val in ("high", "wysoki", "major"):
                severity_colors.append("#F44336")
            elif l_val in ("medium", "sredni", "średni", "normal"):
                severity_colors.append("#FF9800")
            elif l_val in ("low", "niski", "minor"):
                severity_colors.append("#4CAF50")
            else:
                severity_colors.append("#607D8B")

        fig, ax = plt.subplots(figsize=(8, max(4, len(counts) * 0.7)))
        bars = ax.barh(
            counts.index.astype(str),
            counts.values,
            color=severity_colors,
            edgecolor="white",
            height=0.6,
        )
        self._apply_style(ax, title)
        ax.grid(axis="x", linestyle="--", alpha=0.4, color=self.COLORS["grid"])
        ax.grid(axis="y", visible=False)
        ax.xaxis.set_major_locator(mticker.MaxNLocator(integer=True))

        for bar, val in zip(bars, counts.values):
            ax.text(
                bar.get_width() + 0.3,
                bar.get_y() + bar.get_height() / 2,
                str(val),
                va="center",
                fontsize=10,
                fontweight="bold",
                color=self.COLORS["secondary"],
            )

        xlabel = "Liczba błędów" if lang == "pl" else "Bug Count"
        ax.set_xlabel(xlabel, fontsize=10)
        fig.tight_layout()

        return self._save_chart(fig, "bug_severity", project_name)
