# ============================================================
# FILE: .\backend\src\services\report_generator.py
# ============================================================

import os
import json
import re
from datetime import datetime
from pathlib import Path

from weasyprint import HTML, CSS
from markdownify import markdownify as md
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from htmldocx import HtmlToDocx

from src.core.config import Config
from src.core.logger import get_logger
from src.core.exceptions import ExportError


class ReportGenerator:
    """Generates structured Go/No-Go decision reports and exports to PDF, DOCX, or Markdown."""

    def __init__(self, llm_client):
        self.logger = get_logger(self.__class__.__name__)
        self.llm = llm_client
        self.final_output_path = Config.OUTPUT_REPORTS_PATH

        os.makedirs(self.final_output_path, exist_ok=True)

    # ─── Versioning ──────────────────────────────────────────────

    def _get_next_version(self, log_filepath):
        """Reads the version history file and returns the next incremented version string."""
        if os.path.exists(log_filepath):
            try:
                with open(log_filepath, "r", encoding="utf-8") as f:
                    history = json.load(f)
                    if history:
                        last_version = str(history[-1].get("version", "1.0"))
                        if "." not in last_version:
                            last_version = f"{last_version}.0"
                        major, minor = last_version.split(".")
                        return f"{major}.{int(minor) + 1}"
            except Exception as e:
                self.logger.warning(f"Could not read version history: {e}")
        return "1.0"

    def _save_version_entry(self, log_filepath, version, filename, author):
        """Appends a new version entry to the version history JSON file."""
        history = []
        if os.path.exists(log_filepath):
            try:
                with open(log_filepath, "r", encoding="utf-8") as f:
                    history = json.load(f)
            except Exception:
                pass

        history.append(
            {
                "version": version,
                "filename": filename,
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "author": author,
                "status": "APPROVED",
            }
        )

        with open(log_filepath, "w", encoding="utf-8") as f:
            json.dump(history, f, indent=4)

    # ─── Localization helpers (bilingual user-facing labels) ─────

    def _labels(self, lang):
        """Returns a dict of localized labels for report sections."""
        if lang == "pl":
            return {
                "title": "Raport Decyzyjny GO/NO-GO",
                "version": "Wersja",
                "author": "Autor",
                "date": "Data",
                "project": "Projekt",
                "attachments": "Załączniki: Wykresy",
                "page": "Strona",
                "confidential": "DOKUMENT POUFNY",
                "generated": "Wygenerowano automatycznie przez QA Decision Engine",
            }
        return {
            "title": "Go/No-Go Decision Report",
            "version": "Version",
            "author": "Author",
            "date": "Date",
            "project": "Project",
            "attachments": "Attachments: Charts",
            "page": "Page",
            "confidential": "CONFIDENTIAL DOCUMENT",
            "generated": "Auto-generated by QA Decision Engine",
        }

    # ─── HTML Preparator ─────────────────────────────────────────

    def _prepare_html_content(self, raw_html: str) -> str:
        """
        Cleans empty lines from Quill, detects Decision headers
        and replaces them with formatted HTML badges.
        """
        # Quill często zostawia puste linie, które brzydko wyglądają na PDFie
        cleaned_html = raw_html.replace("<p><br></p>", "")

        def replacer(match):
            prefix = match.group(1)
            decision = match.group(2).upper()
            color = "#4CAF50" if decision == "GO" else "#F44336"
            # Dodany wrapper wymuszający przerwę (blok z margin-bottom)
            return (
                f'<div style="margin: 20px 0 30px 0;">'
                f'<div style="background-color: {color}; color: white; padding: 10px 24px; '
                f"text-align: center; font-size: 20px; font-weight: bold; border-radius: 8px; "
                f'display: inline-block;">{prefix}: {decision}</div>'
                f"</div>"
            )

        processed_html = re.sub(
            r"<h2>\s*(.*?(?:Decyzja|Decision)\s*):\s*(GO|NO-GO)\s*</h2>",
            replacer,
            cleaned_html,
            flags=re.IGNORECASE,
        )
        return processed_html

    # ─── PDF export (WEASYPRINT) ─────────────────────────────────

    def export_to_pdf(
        self,
        final_text_html,
        charts_paths,
        custom_name="Report",
        author="User",
        lang="en",
    ):
        """Exports the raw HTML from ReactQuill to a pixel-perfect styled PDF."""
        self.logger.info(f"Starting PDF export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(self.final_output_path, "version_history.json")
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.pdf"
            filepath = os.path.join(self.final_output_path, filename)

            content_html = self._prepare_html_content(final_text_html)

            # Generowanie HTML dla wykresów (z użyciem poprawnych ścieżek URI)
            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            charts_html = ""
            if valid_charts:
                charts_html = f'<div class="page-break"></div><h2 class="section-title">{labels["attachments"]}</h2>'
                for chart in valid_charts:
                    # WeasyPrint na Windowsie wymaga prawidłowego URL 'file:///'
                    file_uri = Path(chart).resolve().as_uri()
                    charts_html += f'<div style="text-align: center; margin-top: 30px;"><img src="{file_uri}" class="chart-img" /></div>'

            # Kompletny szablon HTML dla WeasyPrint
            html_template = f"""
            <!DOCTYPE html>
            <html lang="{lang}">
            <head>
                <meta charset="UTF-8">
                <style>
                    @page {{
                        size: A4;
                        margin: 25mm 20mm;
                        @bottom-center {{
                            content: "{labels['generated']} | {labels['page']} " counter(page) " / " counter(pages);
                            font-size: 8pt;
                            color: #94a3b8;
                            border-top: 1px solid #e2e8f0;
                            padding-top: 5mm;
                        }}
                        @top-center {{
                            content: "{labels['confidential']}";
                            font-size: 8pt;
                            color: #cbd5e1;
                        }}
                    }}
                    body {{
                        font-family: 'Helvetica', 'Arial', sans-serif;
                        color: #1e293b;
                        line-height: 1.6;
                        font-size: 11pt;
                    }}
                    .banner {{
                        position: fixed; top: -25mm; left: -20mm; right: -20mm; height: 6mm; background-color: #e3000f;
                    }}
                    .title {{
                        font-size: 24pt; font-weight: bold; margin-top: 10mm; margin-bottom: 5mm; text-transform: uppercase; color: #0f172a;
                    }}
                    .metadata {{
                        background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 12px;
                        font-size: 10pt; color: #475569; font-weight: bold; margin-bottom: 10mm; border-radius: 4px;
                    }}
                    h1, h2, h3 {{
                        color: #0f172a; margin-top: 8mm; margin-bottom: 4mm;
                    }}
                    h1, h2 {{
                        border-left: 4px solid #e3000f; padding-left: 10px;
                    }}
                    .chart-img {{
                        width: 100%; max-width: 160mm; border: 1px solid #e2e8f0; border-radius: 4px;
                    }}
                    .page-break {{ page-break-before: always; }}
                    
                    /* ReactQuill Editor Styles */
                    ul, ol {{ margin-bottom: 1em; padding-left: 20px; }}
                    blockquote {{ border-left: 4px solid #cbd5e1; margin-left: 0; padding-left: 1em; color: #64748b; font-style: italic; }}
                    pre.ql-syntax {{ background-color: #f1f5f9; padding: 10px; border-radius: 4px; font-family: monospace; font-size: 9pt; white-space: pre-wrap; }}
                    .ql-align-center {{ text-align: center; }}
                    .ql-align-right {{ text-align: right; }}
                    .ql-align-justify {{ text-align: justify; }}

                    /* Nadpisanie tabel - "Squish" na wierszach */
                    table {{
                        width: 100%;
                        border-collapse: collapse;
                        margin-top: 10px;
                        margin-bottom: 20px;
                    }}
                    th, td {{
                        padding: 4px 8px !important; /* Zmniejsza wysokość komórki */
                        line-height: 1.2 !important; /* Ciasny tekst wewnątrz tabeli */
                    }}
                </style>
            </head>
            <body>
                <div class="banner"></div>
                <div class="title">{labels['title']}</div>
                <div class="metadata">
                    {labels['project']}: {custom_name} &nbsp;|&nbsp; {labels['version']}: {version} &nbsp;|&nbsp; {labels['author']}: {author} &nbsp;|&nbsp; {labels['date']}: {timestamp_display}
                </div>

                <div class="content">
                    {content_html}
                </div>

                {charts_html}
            </body>
            </html>
            """

            # Render PDF
            HTML(string=html_template).write_pdf(filepath)
            self.logger.info(f"PDF saved: {filepath}")

            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"PDF generation failed: {e}")
            raise ExportError(f"PDF generation failed: {e}")

    # ─── DOCX export (HTMLtoDOCX) ────────────────────────────────

    def export_to_docx(
        self,
        final_text_html,
        charts_paths,
        custom_name="Report",
        author="User",
        lang="en",
    ):
        """Exports the raw HTML from ReactQuill to DOCX keeping formats."""
        self.logger.info(f"Starting DOCX export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(
                self.final_output_path, "docx_version_history.json"
            )
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.docx"
            filepath = os.path.join(self.final_output_path, filename)

            doc = Document()

            # Global Style
            style = doc.styles["Normal"]
            style.font.name = "Calibri"
            style.font.size = Pt(11)

            # Header
            doc.add_heading(labels["title"].upper(), level=0)
            meta_p = doc.add_paragraph()
            meta_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
            meta_run = meta_p.add_run(
                f"{labels['project']}: {custom_name}  |  {labels['version']}: {version}  |  "
                f"{labels['author']}: {author}  |  {labels['date']}: {timestamp_display}"
            )
            meta_run.font.color.rgb = RGBColor(100, 116, 139)

            doc.add_paragraph("")

            # Wrzucamy HTML prosto z ReactQuilla do parsera DOCX
            new_parser = HtmlToDocx()
            content_html = self._prepare_html_content(final_text_html)
            new_parser.add_html_to_document(content_html, doc)

            # Wykresy jako obrazy z plików
            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                doc.add_page_break()
                doc.add_heading(labels["attachments"], level=1)
                for chart in valid_charts:
                    doc.add_picture(chart, width=Inches(6.0))
                    doc.add_paragraph("")

            # Footer text at the end (Word doesn't easily support simple footers via python-docx script, so append)
            doc.add_paragraph("---")
            footer = doc.add_paragraph(labels["generated"])
            footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
            footer.style.font.size = Pt(8)

            doc.save(filepath)
            self.logger.info(f"DOCX saved: {filepath}")

            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"DOCX generation failed: {e}")
            raise ExportError(f"DOCX generation failed: {e}")

    # ─── Markdown export (MARKDOWNIFY) ───────────────────────────

    def export_to_md(
        self,
        final_text_html,
        charts_paths,
        custom_name="Report",
        author="User",
        lang="en",
    ):
        """Exports the raw HTML from ReactQuill back to Markdown."""
        self.logger.info(f"Starting Markdown export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(
                self.final_output_path, "md_version_history.json"
            )
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.md"
            filepath = os.path.join(self.final_output_path, filename)

            # Konwersja HTML -> Markdown (ATX headers to styl `# Nagłówek`)
            md_content = md(final_text_html, heading_style="ATX")

            lines = [
                f"# {labels['title']}",
                "",
                f"| {labels['project']} | {labels['version']} | {labels['author']} | {labels['date']} |",
                "|---|---|---|---|",
                f"| {custom_name} | {version} | {author} | {timestamp_display} |",
                "",
                "---",
                "",
                md_content.strip(),
                "",
            ]

            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                lines.extend(["---", "", f"## {labels['attachments']}", ""])
                for chart in valid_charts:
                    chart_name = os.path.basename(chart)
                    lines.extend([f"![{chart_name}]({chart_name})", ""])

            lines.extend(["---", f"*{labels['generated']}*"])

            with open(filepath, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))

            self.logger.info(f"Markdown saved: {filepath}")
            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"Markdown generation failed: {e}")
            raise ExportError(f"Markdown generation failed: {e}")

    def generate_structured_draft(
        self,
        historical_cache,
        rag_context,
        parsed_test_data,
        user_risks,
        project_name,
        lang="pl",
    ):
        """
        Generates a structured JSON draft of the Go/No-Go report via LLM.

        Args:
            historical_cache: Previous draft cache (if any) for context.
            rag_context: RAG-retrieved context from project/chat documents.
            parsed_test_data: Markdown-formatted test data tables.
            user_risks: User-provided risk notes or remarks.
            project_name: Name/ID of the project or chat.
            lang: Language for the report content.

        Returns:
            dict with keys: summary, test_analysis, risks_eval, decision, justification.
        """
        self.logger.info(f"Generating structured JSON report (lang: {lang})")

        if lang == "pl":
            history_str = "To jest pierwsza wersja (draft) raportu. Nie ma jeszcze decyzji ostatecznej."
            if historical_cache and historical_cache.get("data"):
                prev_status = historical_cache["data"].get("decision", "Nieznany")
                prev_risks = historical_cache["data"].get("risks_eval", "Brak")
                history_str = f"To jest kolejna iteracja (aktualizacja) raportu. Poprzednia decyzja to: {prev_status}.\nPoprzednie zidentyfikowane ryzyka: {prev_risks}."

            system_prompt = (
                "Jesteś Głównym Inżynierem QA i doradcą technicznym. Ostateczną instancją decyzyjną jest Użytkownik.\n"
                "ZASADA NADRZĘDNA: Jeśli w sekcji [UWAGI UŻYTKOWNIKA] człowiek jawnie akceptuje ryzyka lub nakazuje zmianę decyzji, MUSISZ ustawić 'GO'. "
                "W polu 'justification' wyjaśnij wtedy zwięźle, że ryzyko zostało zaakceptowane biznesowo i wylistuj te zaakceptowane błędy.\n"
                "Zwróć odpowiedź WYŁĄCZNIE jako surowy, poprawny obiekt JSON (bez znaczników ```json). "
                "W wartościach tekstowych używaj formatowania Markdown (pogrubienia, listy), aby tekst był maksymalnie czytelny.\n"
                "!!! BARDZO WAŻNE - ZWIĘZŁOŚĆ I KONKRET !!!\n"
                "Pisz stylem zwięzłym, biznesowym i inżynieryjnym. Unikaj jakichkolwiek powtórzeń. Jeśli informacja (np. o braku błędów krytycznych) padła w podsumowaniu, nie powtarzaj jej w uzasadnieniu. Skup się na faktach, liczbach i konkretnych defektach. Żadnego lania wody."
            )

            user_prompt = f"""
                            Wygeneruj profesjonalny i zwięzły raport w formacie JSON zachowując te klucze:
                            - "summary": (string) Krótkie podsumowanie menedżerskie (max 3-4 zdania). Kontekst, ogólny stan i główny wniosek.
                            - "test_analysis": (array) Lista obiektów JSON: "test_name", "value", "filename". Uwzględnij wszystkie wiersze z [ZPARSOWANE WYNIKI TESTÓW].
                            - "chart_data": (object) Obiekt z tablicami: "tests" (component, status: "Passed"/"Failed"/"Skipped"/"Blocked") oraz "bugs" (severity: "Krytyczny"/"Wysoki"/"Średni"/"Niski", component).
                            - "test_analysis_summary": (string) Zwięzła analiza wyników (max 4-5 zdań). Interpretacja danych, wzorce błędów, ewentualne odchylenia (np. słabsze systemy).
                            - "risks_eval": (string) Ocena ryzyk. Krótko i na temat: czy coś zagraża wdrożeniu i jakie jest stanowisko użytkownika.
                            - "decision": (string) "GO" lub "NO-GO",
                            - "justification": (string) Jednoznaczne, 2-3 zdaniowe uzasadnienie decyzji oparte na twardych danych testowych.
                            - "assistant_reply": (string) Krótka, naturalna odpowiedź w czacie informująca o wygenerowaniu draftu i możliwości naniesienia poprawek.

                            [GLOBALNE ZASADY BIZNESOWE (RAG)]
                            {rag_context}

                            [KONTEKST Z POPRZEDNICH WERSJI RAPORTU]
                            {history_str}

                            [ZPARSOWANE WYNIKI TESTÓW]
                            {parsed_test_data}

                            [UWAGI UŻYTKOWNIKA (PRIORYTET NADRZĘDNY)]
                            {user_risks}
                            """
            fallback_summary = "Błąd parsowania JSON"
            fallback_justification = "Błąd po stronie modelu AI (niepoprawny format)"

        else:
            history_str = "no historical reports"
            if historical_cache and historical_cache.get("data"):
                prev_status = historical_cache["data"].get("decision", "unknown")
                prev_risks = historical_cache["data"].get("risks_eval", "none")
                history_str = f"Last decision: {prev_status} | Last risks: {prev_risks}"

            system_prompt = (
                "You are a Lead QA Engineer acting as a technical advisor. The User is the ultimate Release Manager.\n"
                "OVERRIDE RULE: If the User in the [USER INPUT] section explicitly accepts risks, commands a decision change, or states that bugs are known/accepted, you MUST set the decision to 'GO'. "
                "In such cases, use the 'justification' field to state that despite technical failures, the risks were business-accepted by the User AND EXPLICITLY LIST ALL SPECIFIC BUGS/RISKS (e.g., performance issues, specific component failures) that the User decided to ignore/accept.\n"
                "Return the response STRICTLY as a valid JSON object (do not use ```json code blocks). INSIDE the text fields (like summary, justification), YOU MUST USE rich Markdown formatting (bolding, bullet points, headers) to make the report structured and readable.\n"
                "!!! CRITICAL VOLUME REQUIREMENT !!!\n"
                "The text fields in your JSON ('summary', 'test_analysis_summary', 'risks_eval', 'justification') MUST BE EXTREMELY LONG AND DETAILED. "
                "Treat them as extensive, technical analytical essays. Elaborating heavily, providing context, and diving deep into details is highly desired here. "
                "EACH of these fields must contain at least 15-20 long, complex sentences. Short responses will be considered a critical failure."
            )

            user_prompt = f"""
                            Generate a highly detailed and comprehensive report in JSON format keeping exactly these keys:
                            - "summary": (string) VERY LONG TEXT (minimum 300 words). A very detailed, multi-faceted executive summary. Thoroughly describe the context of the tests, the overall system state, key metrics, and the main conclusions drawn from the entire test campaign.
                            - "test_analysis": (array) a list of test results as JSON objects. Each object MUST contain exactly these keys: "test_name", "value", "filename". Iterate through ALL rows from [PARSED TEST RESULTS] and list each test separately. Do not group, do not omit any single test.
                            - "chart_data": (object) An object with two arrays: "tests" and "bugs". 
                                The "tests" array should contain test results, where each object is: {{"component": (string, name of module/system), "status": (string, ONLY one of these values: "Passed", "Failed", "Skipped", "Blocked")}}. 
                                The "bugs" array should contain defects, where each object is: {{"severity": (string, ONLY one of these values: "Critical", "High", "Medium", "Low"), "component": (string, name of module)}}. Extract this data from [PARSED TEST RESULTS].
                            - "test_analysis_summary": (string) VERY LONG TEXT (minimum 300 words). An in-depth, extensive statistical and qualitative analysis of the test results. Interpret the results, identify error patterns, describe any anomalies, and explain in detail what these results mean for overall system stability.
                            - "risks_eval": (string) VERY LONG TEXT (minimum 300 words). A comprehensive and very lengthy risk evaluation. Deeply analyze technical and business risks, the impact of potential bugs on the production environment, security, and performance. Detail the user's stance on these risks.
                            - "decision": (string) exactly "GO" or "NO-GO",
                            - "justification": (string) VERY LONG TEXT (minimum 300 words). An exhaustive, extensive justification for the final decision. Build a full argumentation based on test results, identified risks, and business consequences. (Remember to respect the user's authority from the [USER NOTES] section!).
                            - "assistant_reply": (string) A short, natural, and friendly chat response. Explain to the user that you have generated a comprehensive draft report (and state the decision). Inform them that this is a draft and they can request adjustments, risk acceptance, or a decision change in their next message.

                            [GLOBAL BUSINESS RULES (RAG)]
                            {rag_context}

                            [HISTORY CONTEXT FROM PREVIOUS DRAFTS]
                            {history_str}

                            [PARSED TEST RESULTS]
                            {parsed_test_data}

                            [USER NOTES (TOP PRIORITY)]
                            {user_risks}
                            """
            fallback_summary = "JSON parsing error"
            fallback_justification = "LLM-side error (incorrect format)"

        raw_response = self.llm.generate_response(
            system_prompt,
            user_prompt,
            temperature=0.2,
            max_tokens=10000,
            force_json=True,
        )

        cleaned_response = raw_response.strip()
        match = re.search(r"\{.*\}", cleaned_response, re.DOTALL)
        if match:
            cleaned_response = match.group(0)

        try:
            return json.loads(cleaned_response)
        except json.JSONDecodeError as e:
            self.logger.error(
                f"LLM did not return valid JSON: {raw_response[:250]}... {e}"
            )
            return {
                "summary": fallback_summary,
                "test_analysis": [],
                "test_analysis_summary": "",
                "risks_eval": "",
                "decision": "NO-GO",
                "justification": fallback_justification,
            }
