# report_generator.py

import os
import json
import re

from datetime import datetime
from fpdf import FPDF
from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

from src.core.config import Config
from src.core.logger import get_logger
from src.core.exceptions import ExportError


class ReportGenerator:
    def __init__(self, llm_client):
        self.logger = get_logger(self.__class__.__name__)
        self.llm = llm_client
        self.final_output_path = Config.OUTPUT_REPORTS_PATH

        current_dir = os.path.dirname(os.path.abspath(__file__))
        self.font_regular = os.path.join(current_dir, "..", "utils", "fonts", "Roboto-Regular.ttf")
        self.font_bold = os.path.join(current_dir, "..", "utils", "fonts", "Roboto-Bold.ttf")

        os.makedirs(self.final_output_path, exist_ok=True)

    # ─── versioning ──────────────────────────────────────────────

    def _get_next_version(self, log_filepath):
        if os.path.exists(log_filepath):
            try:
                with open(log_filepath, "r", encoding="utf-8") as f:
                    history = json.load(f)
                    if history:
                        last_version = str(history[-1].get("version", "1.0"))
                        if "." not in last_version:
                            last_version = f"{last_version}.0"
                        major, minor = last_version.split(".")
                        return f"{major}.{int(minor) + 1}"
            except Exception as e:
                self.logger.warning(f"Could not read version history: {e}")
        return "1.0"

    def _save_version_entry(self, log_filepath, version, filename, author):
        history = []
        if os.path.exists(log_filepath):
            try:
                with open(log_filepath, "r", encoding="utf-8") as f:
                    history = json.load(f)
            except Exception:
                pass

        history.append({
            "version": version,
            "filename": filename,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "author": author,
            "status": "APPROVED"
        })

        with open(log_filepath, "w", encoding="utf-8") as f:
            json.dump(history, f, indent=4)

    # ─── localization helpers ────────────────────────────────────

    def _labels(self, lang):
        if lang == "pl":
            return {
                "title": "Raport Decyzyjny GO/NO-GO",
                "version": "Wersja",
                "author": "Autor",
                "date": "Data",
                "project": "Projekt",
                "summary": "Podsumowanie",
                "test_analysis": "Analiza Testów",
                "risks_eval": "Ocena Ryzyk",
                "decision": "Decyzja",
                "justification": "Uzasadnienie",
                "attachments": "Załączniki: Wykresy",
                "page": "Strona",
                "confidential": "DOKUMENT POUFNY",
                "generated": "Wygenerowano automatycznie przez QA Decision Engine",
            }
        return {
            "title": "Go/No-Go Decision Report",
            "version": "Version",
            "author": "Author",
            "date": "Date",
            "project": "Project",
            "summary": "Summary",
            "test_analysis": "Test Analysis",
            "risks_eval": "Risk Evaluation",
            "decision": "Decision",
            "justification": "Justification",
            "attachments": "Attachments: Charts",
            "page": "Page",
            "confidential": "CONFIDENTIAL DOCUMENT",
            "generated": "Auto-generated by QA Decision Engine",
        }

    # ─── LLM draft generation ───────────────────────────────────

    def generate_structured_draft(self, historical_cache, rag_context, parsed_test_data,
                                  user_risks, project_name, lang="pl"):
        self.logger.info(f"Generating structured JSON report (lang: {lang})")

        if lang == "pl":
            history_str = "brak historycznych raportow"
            if historical_cache and historical_cache.get("data"):
                prev_status = historical_cache["data"].get("decision", "Nieznany")
                prev_risks = historical_cache["data"].get("risks_eval", "Brak")
                history_str = f"Ostatnia decyzja: {prev_status}. Poprzednie ryzyka: {prev_risks}."

            system_prompt = (
                "Jestes glownym inzynierem QA. Twoim zadaniem jest analityczna ocena wdrozenia. "
                "MUSISZ zwrocic odpowiedz jako poprawny obiekt JSON. "
                "Nie dodawaj zadnego formatowania Markdown wokol JSONa."
            )
            user_prompt = f"""
Wygeneruj strukture raportu decyzyjnego w formacie JSON z nastepujacymi kluczami:
- "summary": (string) krotkie podsumowanie wynikow,
- "test_analysis": (string) wnioski z przeprowadzonych testow,
- "risks_eval": (string) ocena ryzyk podanych przez uzytkownika oraz ryzyk z testow,
- "decision": (string) dokladnie "GO" lub "NO-GO",
- "justification": (string) dlaczego podjeto taka decyzje (uwzglednij kontekst historyczny i reguly biznesowe).

[REGULY DECYZYJNE Z HISTORYCZNYCH RAPORTOW]
{rag_context}

[KONTEKST HISTORYCZNY PROJEKTU]
{history_str}

[ZPARSOWANE WYNIKI TESTOW]
{parsed_test_data}

[RYZYKA UZYTKOWNIKA]
{user_risks}
"""
            fallback_summary = "Blad parsowania JSON"
            fallback_justification = "Blad po stronie modelu AI (niepoprawny format)"

        else:
            history_str = "no historical reports"
            if historical_cache and historical_cache.get("data"):
                prev_status = historical_cache["data"].get("decision", "unknown")
                prev_risks = historical_cache["data"].get("risks_eval", "none")
                history_str = f"Last decision: {prev_status} | Last risks: {prev_risks}"

            system_prompt = (
                "You are a lead QA engineer. Your task is to analytically evaluate the deployment. "
                "You MUST return the response as a valid JSON object."
            )
            user_prompt = f"""
Generate the structure of the decision report in JSON format.
NOTE: Keep the JSON keys exactly as specified below, and write the values in professional English.

Required keys:
- "summary": brief summary of the results,
- "test_analysis": conclusions from the executed tests,
- "risks_eval": evaluation of user-reported risks,
- "decision": exactly "GO" or "NO-GO",
- "justification": rationale behind the decision (include historical context and business rules).

[DECISION RULES FROM HISTORICAL REPORTS]
{rag_context}

[HISTORICAL PROJECT CONTEXT]
{history_str}

[PARSED TEST DATA]
{parsed_test_data}

[USER RISKS]
{user_risks}
"""
            fallback_summary = "JSON parsing error"
            fallback_justification = "LLM-side error (incorrect format)"

        raw_response = self.llm.generate_response(
            system_prompt, user_prompt,
            temperature=0.1, max_tokens=2000, force_json=True
        )

        cleaned_response = raw_response.strip()
        match = re.search(r'\{.*\}', cleaned_response, re.DOTALL)
        if match:
            cleaned_response = match.group(0)

        try:
            return json.loads(cleaned_response)
        except json.JSONDecodeError as e:
            self.logger.error(f"LLM did not return valid JSON: {raw_response[:250]}... {e}")
            return {
                "summary": fallback_summary,
                "test_analysis": "",
                "risks_eval": "",
                "decision": "NO-GO",
                "justification": fallback_justification
            }

    # ─── PDF export ──────────────────────────────────────────────

    def export_to_pdf(self, final_text, charts_paths, custom_name="Report",
                      author="User", lang="en"):
        self.logger.info(f"Starting PDF export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(self.final_output_path, "version_history.json")
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.pdf"
            filepath = os.path.join(self.final_output_path, filename)

            pdf = _StyledPDF(labels, orientation="P", unit="mm", format="A4")
            pdf.alias_nb_pages()
            
            has_roboto = os.path.exists(self.font_regular)
            has_roboto_bold = os.path.exists(self.font_bold)

            if has_roboto:
                pdf.add_font("Roboto", "", self.font_regular, uni=True)
                if has_roboto_bold:
                    pdf.add_font("Roboto", "B", self.font_bold, uni=True)
                else:
                    pdf.add_font("Roboto", "B", self.font_regular, uni=True)
                pdf.default_font = "Roboto"
            else:
                pdf.default_font = "Helvetica"
                self.logger.warning("Roboto font not found, falling back to Helvetica")

            pdf.set_auto_page_break(auto=True, margin=25)
            pdf.add_page()

            # ── Cover / Header Block ──
            pdf.set_fill_color(227, 0, 15)  # orlen red
            pdf.rect(0, 0, 210, 55, "F")
            pdf.set_text_color(255, 255, 255)
            pdf.set_font(pdf.default_font, "B", 22)
            pdf.set_y(14)
            pdf.cell(0, 12, labels["title"], ln=True, align="C")
            pdf.set_font(pdf.default_font, "", 11)
            pdf.cell(0, 7, f'{labels["project"]}: {custom_name}', ln=True, align="C")
            pdf.cell(0, 7,
                     f'{labels["version"]}: {version}  |  '
                     f'{labels["author"]}: {author}  |  '
                     f'{labels["date"]}: {timestamp_display}',
                     ln=True, align="C")

            pdf.set_text_color(45, 45, 45)
            pdf.ln(20)

            # ── Parse sections from final_text ──
            sections = self._parse_sections_from_text(final_text)

            section_keys = ["summary", "test_analysis", "risks_eval", "decision", "justification"]
            for key in section_keys:
                heading = labels.get(key, key)
                body = sections.get(key, "")
                if not body:
                    continue

                # Section heading
                pdf.set_font(pdf.default_font, "B", 13)
                pdf.set_text_color(227, 0, 15)
                pdf.cell(0, 10, heading, ln=True)
                pdf.set_draw_color(227, 0, 15)
                pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 180, pdf.get_y())
                pdf.ln(3)

                # Decision badge
                if key == "decision":
                    self._pdf_decision_badge(pdf, body.strip())
                    pdf.ln(6)
                    continue

                # Body text
                pdf.set_font(pdf.default_font, "", 10)
                pdf.set_text_color(45, 45, 45)
                pdf.multi_cell(0, 6, body.strip())
                pdf.ln(6)

            # ── Charts ──
            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                pdf.add_page()
                pdf.set_font(pdf.default_font, "B", 14)
                pdf.set_text_color(45, 45, 45)
                pdf.cell(0, 10, labels["attachments"], ln=True)
                pdf.ln(4)

                for chart in valid_charts:
                    if pdf.get_y() > 200:
                        pdf.add_page()
                    pdf.image(chart, x=15, w=180)
                    pdf.ln(8)

            pdf.output(filepath)
            self.logger.info(f"PDF saved: {filepath}")

            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"PDF generation failed: {e}")
            raise ExportError(f"PDF generation failed: {e}")

    def _pdf_decision_badge(self, pdf, decision_text):
        """Renders a colored GO / NO-GO badge in the PDF."""
        is_go = decision_text.upper().strip() == "GO"
        if is_go:
            pdf.set_fill_color(76, 175, 80)
        else:
            pdf.set_fill_color(244, 67, 54)

        pdf.set_text_color(255, 255, 255)
        pdf.set_font(pdf.default_font, "B", 18)

        badge_w = 60
        x = (210 - badge_w) / 2
        pdf.set_x(x)
        pdf.cell(badge_w, 14, decision_text.upper(), ln=True, align="C", fill=True)
        pdf.set_text_color(45, 45, 45)

    # ─── DOCX export ─────────────────────────────────────────────

    def export_to_docx(self, final_text, charts_paths, custom_name="Report",
                       author="User", lang="en"):
        self.logger.info(f"Starting DOCX export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(self.final_output_path, "docx_version_history.json")
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.docx"
            filepath = os.path.join(self.final_output_path, filename)

            doc = Document()

            # ── Default style ──
            style = doc.styles["Normal"]
            style.font.name = "Calibri"
            style.font.size = Pt(11)
            style.font.color.rgb = RGBColor(45, 45, 45)
            style.paragraph_format.space_after = Pt(6)

            # ── Header table (simulates a colored banner) ──
            table = doc.add_table(rows=1, cols=1)
            cell = table.cell(0, 0)
            
            p_title = cell.paragraphs[0]
            p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p_title.add_run(labels["title"])
            run.bold = True
            run.font.size = Pt(20)
            run.font.color.rgb = RGBColor(255, 255, 255)

            p_meta = cell.add_paragraph()
            p_meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
            meta_run = p_meta.add_run(
                f'{labels["project"]}: {custom_name}  |  '
                f'{labels["version"]}: {version}  |  '
                f'{labels["author"]}: {author}  |  '
                f'{labels["date"]}: {timestamp_display}'
            )
            meta_run.font.size = Pt(10)
            meta_run.font.color.rgb = RGBColor(255, 255, 255)

            doc.add_paragraph("")

            # ── Sections ──
            sections = self._parse_sections_from_text(final_text)
            section_keys = ["summary", "test_analysis", "risks_eval", "decision", "justification"]

            for key in section_keys:
                heading = labels.get(key, key)
                body = sections.get(key, "")
                if not body:
                    continue

                h = doc.add_heading(heading, level=2)
                for run in h.runs:
                    run.font.color.rgb = RGBColor(227, 0, 15)

                if key == "decision":
                    p = doc.add_paragraph()
                    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    run = p.add_run(f"  {body.strip().upper()}  ")
                    run.bold = True
                    run.font.size = Pt(18)
                    is_go = body.strip().upper() == "GO"
                    run.font.color.rgb = RGBColor(76, 175, 80) if is_go else RGBColor(244, 67, 54)
                else:
                    doc.add_paragraph(body.strip())

            # ── Charts ──
            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                doc.add_page_break()
                h = doc.add_heading(labels["attachments"], level=1)
                for run in h.runs:
                    run.font.color.rgb = RGBColor(45, 45, 45)

                for chart in valid_charts:
                    doc.add_picture(chart, width=Inches(6.2))
                    doc.add_paragraph("")

            # ── Footer ──
            footer_p = doc.add_paragraph()
            footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            footer_run = footer_p.add_run(labels["generated"])
            footer_run.font.size = Pt(8)
            footer_run.font.color.rgb = RGBColor(150, 150, 150)

            doc.save(filepath)
            self.logger.info(f"DOCX saved: {filepath}")

            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"DOCX generation failed: {e}")
            raise ExportError(f"DOCX generation failed: {e}")

    # ─── Markdown export ─────────────────────────────────────────

    def export_to_md(self, final_text, charts_paths, custom_name="Report",
                     author="User", lang="en"):
        self.logger.info(f"Starting Markdown export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(self.final_output_path, "md_version_history.json")
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.md"
            filepath = os.path.join(self.final_output_path, filename)

            sections = self._parse_sections_from_text(final_text)

            lines = [
                f"# {labels['title']}",
                "",
                f"| {labels['project']} | {labels['version']} | {labels['author']} | {labels['date']} |",
                "|---|---|---|---|",
                f"| {custom_name} | {version} | {author} | {timestamp_display} |",
                "",
                "---",
                "",
            ]

            section_keys = ["summary", "test_analysis", "risks_eval", "decision", "justification"]
            for key in section_keys:
                heading = labels.get(key, key)
                body = sections.get(key, "")
                if not body:
                    continue

                lines.append(f"## {heading}")
                lines.append("")

                if key == "decision":
                    is_go = body.strip().upper() == "GO"
                    emoji = "✅" if is_go else "❌"
                    lines.append(f"### {emoji} **{body.strip().upper()}**")
                else:
                    lines.append(body.strip())

                lines.append("")

            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                lines.append("---")
                lines.append("")
                lines.append(f"## {labels['attachments']}")
                lines.append("")
                for chart in valid_charts:
                    chart_name = os.path.basename(chart)
                    lines.append(f"![{chart_name}]({chart})")
                    lines.append("")

            lines.append("---")
            lines.append(f"*{labels['generated']}*")

            with open(filepath, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))

            self.logger.info(f"Markdown saved: {filepath}")
            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"Markdown generation failed: {e}")
            raise ExportError(f"Markdown generation failed: {e}")

    # ─── Helpers ─────────────────────────────────────────────────

    def _parse_sections_from_text(self, text: str) -> dict:
        """
        Parses the concatenated export text back into named sections.

        Looks for ## headings and maps them to known keys.
        """
        result = {
            "summary": "",
            "test_analysis": "",
            "risks_eval": "",
            "decision": "",
            "justification": "",
        }

        heading_map = {
            "podsumowanie": "summary",
            "summary": "summary",
            "analiza testow": "test_analysis",
            "analiza testów": "test_analysis",
            "test analysis": "test_analysis",
            "ocena ryzyk": "risks_eval",
            "risk evaluation": "risks_eval",
            "decyzja": "decision",
            "decision": "decision",
            "uzasadnienie": "justification",
            "justification": "justification",
        }

        current_key = None
        current_lines = []

        for line in text.split("\n"):
            heading_match = re.match(r"^##\s+(.+)$", line.strip())
            if heading_match:
                if current_key:
                    result[current_key] = "\n".join(current_lines).strip()
                    current_lines = []

                raw_heading = heading_match.group(1).strip()
                # Handle "Decyzja: GO" style headings
                clean_heading = re.sub(r":.*$", "", raw_heading).strip().lower()
                current_key = heading_map.get(clean_heading)

                # Extract decision value from heading like "## Decyzja: GO"
                if clean_heading in ("decyzja", "decision") and ":" in raw_heading:
                    decision_val = raw_heading.split(":", 1)[1].strip()
                    result["decision"] = decision_val
            else:
                if current_key:
                    current_lines.append(line)

        if current_key and current_lines:
            result[current_key] = "\n".join(current_lines).strip()

        return result


class _StyledPDF(FPDF):
    """Custom FPDF subclass with headers and footers."""

    def __init__(self, labels, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.labels = labels
        self.default_font = "Helvetica"

    def header(self):
        if self.page_no() > 1:
            self.set_font(self.default_font, "", 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 8, self.labels["confidential"], align="C", ln=True)
            self.set_draw_color(227, 0, 15)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

    def footer(self):
        self.set_y(-20)
        self.set_font(self.default_font, "", 8)
        self.set_text_color(150, 150, 150)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.cell(0, 8,
                  f'{self.labels["generated"]}  |  '
                  f'{self.labels["page"]} {self.page_no()}/{{nb}}',
                  align="C")