# ============================================================
# FILE: .\backend\src\services\report_generator.py
# ============================================================

import os
import json
import re

from datetime import datetime
from fpdf import FPDF
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from src.core.config import Config
from src.core.logger import get_logger
from src.core.exceptions import ExportError


class ReportGenerator:
    """Generates structured Go/No-Go decision reports and exports to PDF, DOCX, or Markdown."""

    def __init__(self, llm_client):
        self.logger = get_logger(self.__class__.__name__)
        self.llm = llm_client
        self.final_output_path = Config.OUTPUT_REPORTS_PATH

        current_dir = os.path.dirname(os.path.abspath(__file__))
        self.font_dir = os.path.join(current_dir, "..", "utils", "fonts")

        self.font_regular = os.path.join(self.font_dir, "Roboto-Regular.ttf")
        self.font_bold = os.path.join(self.font_dir, "Roboto-Bold.ttf")
        self.font_italic = os.path.join(self.font_dir, "Roboto-Italic.ttf")
        self.font_bold_italic = os.path.join(self.font_dir, "Roboto-BoldItalic.ttf")

        os.makedirs(self.final_output_path, exist_ok=True)

    # ─── Versioning ──────────────────────────────────────────────

    def _get_next_version(self, log_filepath):
        """Reads the version history file and returns the next incremented version string."""
        if os.path.exists(log_filepath):
            try:
                with open(log_filepath, "r", encoding="utf-8") as f:
                    history = json.load(f)
                    if history:
                        last_version = str(history[-1].get("version", "1.0"))
                        if "." not in last_version:
                            last_version = f"{last_version}.0"
                        major, minor = last_version.split(".")
                        return f"{major}.{int(minor) + 1}"
            except Exception as e:
                self.logger.warning(f"Could not read version history: {e}")
        return "1.0"

    def _save_version_entry(self, log_filepath, version, filename, author):
        """Appends a new version entry to the version history JSON file."""
        history = []
        if os.path.exists(log_filepath):
            try:
                with open(log_filepath, "r", encoding="utf-8") as f:
                    history = json.load(f)
            except Exception:
                pass

        history.append(
            {
                "version": version,
                "filename": filename,
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "author": author,
                "status": "APPROVED",
            }
        )

        with open(log_filepath, "w", encoding="utf-8") as f:
            json.dump(history, f, indent=4)

    # ─── Localization helpers (bilingual user-facing labels) ─────

    def _labels(self, lang):
        """Returns a dict of localized labels for report sections."""
        if lang == "pl":
            return {
                "title": "Raport Decyzyjny GO/NO-GO",
                "version": "Wersja",
                "author": "Autor",
                "date": "Data",
                "project": "Projekt",
                "summary": "Podsumowanie",
                "test_analysis": "Analiza Testów",
                "risks_eval": "Ocena Ryzyk",
                "decision": "Decyzja",
                "justification": "Uzasadnienie",
                "attachments": "Załączniki: Wykresy",
                "page": "Strona",
                "confidential": "DOKUMENT POUFNY",
                "generated": "Wygenerowano automatycznie przez QA Decision Engine",
            }
        return {
            "title": "Go/No-Go Decision Report",
            "version": "Version",
            "author": "Author",
            "date": "Date",
            "project": "Project",
            "summary": "Summary",
            "test_analysis": "Test Analysis",
            "risks_eval": "Risk Evaluation",
            "decision": "Decision",
            "justification": "Justification",
            "attachments": "Attachments: Charts",
            "page": "Page",
            "confidential": "CONFIDENTIAL DOCUMENT",
            "generated": "Auto-generated by QA Decision Engine",
        }

    # ─── LLM draft generation ───────────────────────────────────

    def generate_structured_draft(
        self,
        historical_cache,
        rag_context,
        parsed_test_data,
        user_risks,
        project_name,
        lang="pl",
    ):
        """
        Generates a structured JSON draft of the Go/No-Go report via LLM.

        Args:
            historical_cache: Previous draft cache (if any) for context.
            rag_context: RAG-retrieved context from project/chat documents.
            parsed_test_data: Markdown-formatted test data tables.
            user_risks: User-provided risk notes or remarks.
            project_name: Name/ID of the project or chat.
            lang: Language for the report content.

        Returns:
            dict with keys: summary, test_analysis, risks_eval, decision, justification.
        """
        self.logger.info(f"Generating structured JSON report (lang: {lang})")

        if lang == "pl":
            history_str = "To jest pierwsza wersja (draft) raportu. Nie ma jeszcze decyzji ostatecznej."
            if historical_cache and historical_cache.get("data"):
                prev_status = historical_cache["data"].get("decision", "Nieznany")
                prev_risks = historical_cache["data"].get("risks_eval", "Brak")
                history_str = f"To jest kolejna iteracja (aktualizacja) raportu. Poprzednia decyzja to: {prev_status}.\nPoprzednie zidentyfikowane ryzyka: {prev_risks}."

            system_prompt = (
                "Jesteś Głównym Inżynierem QA, ale działasz jako doradca techniczny. "
                "Ostateczną instancją decyzyjną (Release Managerem) jest Użytkownik.\n"
                "ZASADA NADRZĘDNA (AUTORYTET UŻYTKOWNIKA): Jeśli w sekcji [UWAGI UŻYTKOWNIKA] człowiek jawnie akceptuje ryzyka, nakazuje zmianę decyzji lub twierdzi, że błędy są znane, MUSISZ bezwzględnie zmienić decyzję na 'GO'. "
                "W takiej sytuacji w polu 'justification' wyjaśnij, że mimo błędów technicznych, ryzyko zostało zaakceptowane biznesowo ORAZ WYMIEŃ KONKRETNIE WSZYSTKIE BŁĘDY/RYZYKA (np. problemy z wydajnością, błędy konkretnych komponentów), które użytkownik zdecydował się zignorować/zaakceptować.\n"
                "Zwróć odpowiedź WYŁĄCZNIE jako surowy, poprawny obiekt JSON. Nie używaj znaczników ```json ani Markdown.\n"
                "!!! BARDZO WAŻNE - EKSTREMALNY WYMÓG OBJĘTOŚCI !!!\n"
                "Wszystkie pola opisowe w JSON ('summary', 'test_analysis_summary', 'risks_eval', 'justification') MUSZĄ BYĆ NIEZWYKLE DŁUGIE I SZCZEGÓŁOWE. "
                "Traktuj je jak rozbudowane eseje analityczne. Lanie wody, opisywanie kontekstu, wskazywanie szczegółów i wielowątkowa analiza są tu bezwzględnie wymagane. "
                "Każde z tych pól musi zawierać co najmniej 15-20 długich, złożonych zdań. Zbyt krótkie odpowiedzi uznane będą za błąd krytyczny."
            )

            user_prompt = f"""
                            Wygeneruj bardzo szczegółowy i wyczerpujący raport w formacie JSON zachowując te klucze:
                            - "summary": (string) BARDZO DŁUGI TEKST (minimum 300 słów). Dogłębne, wieloaspektowe podsumowanie menedżerskie. Opisz dokładnie kontekst testów, ogólny stan systemu, kluczowe metryki oraz główne wnioski płynące z całej kampanii testowej.
                            - "test_analysis": (array) lista wyników testów jako obiekty JSON. Każdy obiekt MUSI zawierać dokładnie te klucze: "test_name", "value", "filename". Przejdź przez WSZYSTKIE wiersze z [ZPARSOWANE WYNIKI TESTÓW] i wypisz każdy test osobno. Nie grupuj, nie pomijaj absolutnie żadnego testu.
                            - "test_analysis_summary": (string) BARDZO DŁUGI TEKST (minimum 300 słów). Pogłębiona, obszerna analiza statystyczna i jakościowa wyników testów. Zinterpretuj wyniki, wskaż wzorce w błędach, opisz ewentualne anomalie i szczegółowo wyjaśnij, co te wyniki oznaczają dla stabilności całego systemu.
                            - "risks_eval": (string) BARDZO DŁUGI TEKST (minimum 300 słów). Kompleksowa ocena ryzyk. Przeanalizuj dogłębnie ryzyka techniczne i biznesowe, wpływ potencjalnych błędów na środowisko produkcyjne, bezpieczeństwo i wydajność. Odnotuj szczegółowo stanowisko użytkownika.
                            - "decision": (string) dokładnie "GO" lub "NO-GO",
                            - "justification": (string) BARDZO DŁUGI TEKST (minimum 300 słów). Wyczerpujące uzasadnienie ostatecznej decyzji. Zbuduj pełną, rozwlekłą argumentację opartą o wyniki testów, zidentyfikowane ryzyka oraz konsekwencje biznesowe. (Pamiętaj o uwzględnieniu autorytetu użytkownika z sekcji [UWAGI UŻYTKOWNIKA]!).
                            - "assistant_reply": (string) Krótka, naturalna i przyjazna odpowiedź w czacie. Wyjaśnij użytkownikowi, że wygenerowałeś obszerny raport (i wskaż decyzję). Poinformuj, że jest to wersja robocza i użytkownik może poprosić o poprawki, zignorowanie ryzyk lub zmianę decyzji w kolejnej wiadomości.

                            [GLOBALNE ZASADY BIZNESOWE (RAG)]
                            {rag_context}

                            [KONTEKST Z POPRZEDNICH WERSJI RAPORTU]
                            {history_str}

                            [ZPARSOWANE WYNIKI TESTÓW]
                            {parsed_test_data}

                            [UWAGI UŻYTKOWNIKA (PRIORYTET NADRZĘDNY)]
                            {user_risks}
                            """
            fallback_summary = "Błąd parsowania JSON"
            fallback_justification = "Błąd po stronie modelu AI (niepoprawny format)"

        else:
            history_str = "no historical reports"
            if historical_cache and historical_cache.get("data"):
                prev_status = historical_cache["data"].get("decision", "unknown")
                prev_risks = historical_cache["data"].get("risks_eval", "none")
                history_str = f"Last decision: {prev_status} | Last risks: {prev_risks}"

            system_prompt = (
                "You are a Lead QA Engineer acting as a technical advisor. The User is the ultimate Release Manager.\n"
                "OVERRIDE RULE: If the User in the [USER INPUT] section explicitly accepts risks, commands a decision change, or states that bugs are known/accepted, you MUST set the decision to 'GO'. "
                "In such cases, use the 'justification' field to state that despite technical failures, the risks were business-accepted by the User AND EXPLICITLY LIST ALL SPECIFIC BUGS/RISKS (e.g., performance issues, specific component failures) that the User decided to ignore/accept.\n"
                "Return the response STRICTLY as a valid JSON object. Do not use ```json or Markdown wrappers.\n"
                "!!! CRITICAL VOLUME REQUIREMENT !!!\n"
                "The text fields in your JSON ('summary', 'test_analysis_summary', 'risks_eval', 'justification') MUST BE EXTREMELY LONG AND DETAILED. "
                "Treat them as extensive, technical analytical essays. Elaborating heavily, providing context, and diving deep into details is highly desired here. "
                "EACH of these fields must contain at least 15-20 long, complex sentences. Short responses will be considered a critical failure."
            )

            user_prompt = f"""
                            Generate a highly detailed and comprehensive report in JSON format keeping exactly these keys:
                            - "summary": (string) VERY LONG TEXT (minimum 300 words). A very detailed, multi-faceted executive summary. Thoroughly describe the context of the tests, the overall system state, key metrics, and the main conclusions drawn from the entire test campaign.
                            - "test_analysis": (array) a list of test results as JSON objects. Each object MUST contain exactly these keys: "test_name", "value", "filename". Iterate through ALL rows from [PARSED TEST RESULTS] and list each test separately. Do not group, do not omit any single test.
                            - "test_analysis_summary": (string) VERY LONG TEXT (minimum 300 words). An in-depth, extensive statistical and qualitative analysis of the test results. Interpret the results, identify error patterns, describe any anomalies, and explain in detail what these results mean for overall system stability.
                            - "risks_eval": (string) VERY LONG TEXT (minimum 300 words). A comprehensive and very lengthy risk evaluation. Deeply analyze technical and business risks, the impact of potential bugs on the production environment, security, and performance. Detail the user's stance on these risks.
                            - "decision": (string) exactly "GO" or "NO-GO",
                            - "justification": (string) VERY LONG TEXT (minimum 300 words). An exhaustive, extensive justification for the final decision. Build a full argumentation based on test results, identified risks, and business consequences. (Remember to respect the user's authority from the [USER NOTES] section!).
                            - "assistant_reply": (string) A short, natural, and friendly chat response. Explain to the user that you have generated a comprehensive draft report (and state the decision). Inform them that this is a draft and they can request adjustments, risk acceptance, or a decision change in their next message.

                            [GLOBAL BUSINESS RULES (RAG)]
                            {rag_context}

                            [HISTORY CONTEXT FROM PREVIOUS DRAFTS]
                            {history_str}

                            [PARSED TEST RESULTS]
                            {parsed_test_data}

                            [USER NOTES (TOP PRIORITY)]
                            {user_risks}
                            """
            fallback_summary = "JSON parsing error"
            fallback_justification = "LLM-side error (incorrect format)"

        raw_response = self.llm.generate_response(
            system_prompt,
            user_prompt,
            temperature=0.5,
            max_tokens=8000,
            force_json=True,
        )

        cleaned_response = raw_response.strip()
        match = re.search(r"\{.*\}", cleaned_response, re.DOTALL)
        if match:
            cleaned_response = match.group(0)

        try:
            return json.loads(cleaned_response)
        except json.JSONDecodeError as e:
            self.logger.error(
                f"LLM did not return valid JSON: {raw_response[:250]}... {e}"
            )
            return {
                "summary": fallback_summary,
                "test_analysis": [],
                "test_analysis_summary": "",
                "risks_eval": "",
                "decision": "NO-GO",
                "justification": fallback_justification,
            }

    # ─── PDF export ──────────────────────────────────────────────

    def export_to_pdf(
        self, final_text, charts_paths, custom_name="Report", author="User", lang="en"
    ):
        """Exports the report to a styled PDF file."""
        self.logger.info(f"Starting PDF export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(self.final_output_path, "version_history.json")
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.pdf"
            filepath = os.path.join(self.final_output_path, filename)

            pdf = _StyledPDF(labels, orientation="P", unit="mm", format="A4")
            pdf.alias_nb_pages()

            if os.path.exists(self.font_regular):
                pdf.add_font("Roboto", style="", fname=self.font_regular)

                if os.path.exists(self.font_bold):
                    pdf.add_font("Roboto", style="B", fname=self.font_bold)

                if os.path.exists(self.font_italic):
                    pdf.add_font("Roboto", style="I", fname=self.font_italic)

                if os.path.exists(self.font_bold_italic):
                    pdf.add_font("Roboto", style="BI", fname=self.font_bold_italic)

                pdf.default_font = "Roboto"
            else:
                pdf.default_font = "Helvetica"
                self.logger.warning("No Roboto fonts found, using default: Helvetica")

            pdf.set_auto_page_break(auto=True, margin=25)
            pdf.add_page()

            # Thin red banner across the top
            pdf.set_fill_color(227, 0, 15)
            pdf.rect(0, 0, 210, 6, "F")

            pdf.ln(12)

            # Main report title
            pdf.set_text_color(30, 41, 59)
            pdf.set_font(pdf.default_font, "B", 24)
            pdf.cell(0, 10, labels["title"].upper(), ln=True, align="L")
            pdf.ln(4)

            # Metadata block
            pdf.set_fill_color(248, 250, 252)
            pdf.set_draw_color(226, 232, 240)
            start_meta_y = pdf.get_y()
            pdf.rect(10, start_meta_y, 190, 14, "FD")

            pdf.set_y(start_meta_y + 3.5)
            pdf.set_x(14)
            pdf.set_font(pdf.default_font, "B", 10)
            pdf.set_text_color(71, 85, 105)

            meta_text = (
                f'{labels["project"]}: {custom_name}   |   '
                f'{labels["version"]}: {version}   |   '
                f'{labels["author"]}: {author}   |   '
                f'{labels["date"]}: {timestamp_display}'
            )
            pdf.cell(0, 7, meta_text, ln=True, align="L")

            pdf.ln(14)

            sections = self._parse_sections_from_text(final_text)

            section_keys = [
                "summary",
                "test_analysis",
                "risks_eval",
                "decision",
                "justification",
            ]

            for key in section_keys:
                heading = labels.get(key, key)
                body = sections.get(key, "")
                if not body:
                    continue

                pdf.set_fill_color(227, 0, 15)
                pdf.rect(10, pdf.get_y() + 1.5, 1.5, 6, "F")
                pdf.set_x(14)
                pdf.set_font(pdf.default_font, "B", 14)
                pdf.set_text_color(30, 41, 59)
                pdf.cell(0, 8, heading, ln=True)
                pdf.ln(2)

                if key == "decision":
                    self._pdf_decision_badge(pdf, body.strip())
                    pdf.ln(6)
                    continue

                if key == "test_analysis":
                    # body here is already a string from _parse_sections_from_text
                    # render as plain text list
                    pdf.set_x(10)
                    pdf.set_font(pdf.default_font, "", 10.5)
                    pdf.set_text_color(51, 65, 85)
                    for line in body.strip().split("\n"):
                        pdf.multi_cell(190, 6.5, line.strip())
                    pdf.ln(5)
                    continue

                pdf.set_x(10)
                pdf.set_font(pdf.default_font, "", 10.5)
                pdf.set_text_color(51, 65, 85)
                pdf.multi_cell(190, 6.5, body.strip())
                pdf.ln(5)

            # Charts attachments
            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                pdf.add_page()

                pdf.set_fill_color(227, 0, 15)
                pdf.rect(10, pdf.get_y() + 1.5, 1.5, 6, "F")
                pdf.set_x(14)
                pdf.set_font(pdf.default_font, "B", 14)
                pdf.set_text_color(30, 41, 59)
                pdf.cell(0, 9, labels["attachments"].upper(), ln=True)
                pdf.ln(6)

                for chart in valid_charts:
                    if pdf.get_y() > 180:
                        pdf.add_page()

                    img_y = pdf.get_y()

                    pdf.set_draw_color(226, 232, 240)
                    pdf.rect(14, img_y - 1, 182, 102, "D")

                    pdf.image(chart, x=15, w=180)
                    pdf.ln(110)

            pdf.output(filepath)
            self.logger.info(f"PDF saved: {filepath}")

            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"PDF generation failed: {e}")
            raise ExportError(f"PDF generation failed: {e}")

    def _pdf_decision_badge(self, pdf, decision_text):
        """Renders a colored GO / NO-GO badge in the PDF."""
        is_go = decision_text.upper().strip() == "GO"
        if is_go:
            pdf.set_fill_color(76, 175, 80)
        else:
            pdf.set_fill_color(244, 67, 54)

        pdf.set_text_color(255, 255, 255)
        pdf.set_font(pdf.default_font, "B", 18)

        badge_w = 60
        x = (210 - badge_w) / 2
        pdf.set_x(x)
        pdf.cell(badge_w, 14, decision_text.upper(), ln=True, align="C", fill=True)
        pdf.set_text_color(45, 45, 45)

    # ─── DOCX export ─────────────────────────────────────────────

    def export_to_docx(
        self, final_text, charts_paths, custom_name="Report", author="User", lang="en"
    ):
        """Exports the report to a styled DOCX file."""
        self.logger.info(f"Starting DOCX export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(
                self.final_output_path, "docx_version_history.json"
            )
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.docx"
            filepath = os.path.join(self.final_output_path, filename)

            doc = Document()

            # Default style
            style = doc.styles["Normal"]
            style.font.name = "Calibri"
            style.font.size = Pt(11)
            style.font.color.rgb = RGBColor(45, 45, 45)
            style.paragraph_format.space_after = Pt(6)

            # Header table (simulates a colored banner)
            table = doc.add_table(rows=1, cols=1)
            cell = table.cell(0, 0)

            p_title = cell.paragraphs[0]
            p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = p_title.add_run(labels["title"])
            run.bold = True
            run.font.size = Pt(20)
            run.font.color.rgb = RGBColor(255, 255, 255)

            p_meta = cell.add_paragraph()
            p_meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
            meta_run = p_meta.add_run(
                f'{labels["project"]}: {custom_name}  |  '
                f'{labels["version"]}: {version}  |  '
                f'{labels["author"]}: {author}  |  '
                f'{labels["date"]}: {timestamp_display}'
            )
            meta_run.font.size = Pt(10)
            meta_run.font.color.rgb = RGBColor(255, 255, 255)

            doc.add_paragraph("")

            # Sections
            sections = self._parse_sections_from_text(final_text)
            section_keys = [
                "summary",
                "test_analysis",
                "risks_eval",
                "decision",
                "justification",
            ]

            for key in section_keys:
                heading = labels.get(key, key)
                body = sections.get(key, "")
                if not body:
                    continue

                h = doc.add_heading(heading, level=2)
                for run in h.runs:
                    run.font.color.rgb = RGBColor(227, 0, 15)

                if key == "decision":
                    p = doc.add_paragraph()
                    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    run = p.add_run(f"  {body.strip().upper()}  ")
                    run.bold = True
                    run.font.size = Pt(18)
                    is_go = body.strip().upper() == "GO"
                    run.font.color.rgb = (
                        RGBColor(76, 175, 80) if is_go else RGBColor(244, 67, 54)
                    )
                else:
                    doc.add_paragraph(body.strip())

            # Charts
            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                doc.add_page_break()
                h = doc.add_heading(labels["attachments"], level=1)
                for run in h.runs:
                    run.font.color.rgb = RGBColor(45, 45, 45)

                for chart in valid_charts:
                    doc.add_picture(chart, width=Inches(6.2))
                    doc.add_paragraph("")

            # Footer
            footer_p = doc.add_paragraph()
            footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            footer_run = footer_p.add_run(labels["generated"])
            footer_run.font.size = Pt(8)
            footer_run.font.color.rgb = RGBColor(150, 150, 150)

            doc.save(filepath)
            self.logger.info(f"DOCX saved: {filepath}")

            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"DOCX generation failed: {e}")
            raise ExportError(f"DOCX generation failed: {e}")

    # ─── Markdown export ─────────────────────────────────────────

    def export_to_md(
        self, final_text, charts_paths, custom_name="Report", author="User", lang="en"
    ):
        """Exports the report to a Markdown file."""
        self.logger.info(f"Starting Markdown export for project: {custom_name}")

        try:
            timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
            timestamp_display = datetime.now().strftime("%Y-%m-%d %H:%M")
            log_filepath = os.path.join(
                self.final_output_path, "md_version_history.json"
            )
            version = self._get_next_version(log_filepath)
            labels = self._labels(lang)

            clean_name = custom_name.replace(" ", "_")
            clean_author = author.replace(" ", "_")
            filename = f"{clean_name}_{clean_author}_{timestamp_file}.md"
            filepath = os.path.join(self.final_output_path, filename)

            sections = self._parse_sections_from_text(final_text)

            lines = [
                f"# {labels['title']}",
                "",
                f"| {labels['project']} | {labels['version']} | {labels['author']} | {labels['date']} |",
                "|---|---|---|---|",
                f"| {custom_name} | {version} | {author} | {timestamp_display} |",
                "",
                "---",
                "",
            ]

            section_keys = [
                "summary",
                "test_analysis",
                "risks_eval",
                "decision",
                "justification",
            ]
            for key in section_keys:
                heading = labels.get(key, key)
                body = sections.get(key, "")
                if not body:
                    continue

                lines.append(f"## {heading}")
                lines.append("")

                if key == "decision":
                    is_go = body.strip().upper() == "GO"
                    emoji = "✅" if is_go else "❌"
                    lines.append(f"### {emoji} **{body.strip().upper()}**")
                else:
                    lines.append(body.strip())

                lines.append("")

            valid_charts = [c for c in charts_paths if os.path.exists(c)]
            if valid_charts:
                lines.append("---")
                lines.append("")
                lines.append(f"## {labels['attachments']}")
                lines.append("")
                for chart in valid_charts:
                    chart_name = os.path.basename(chart)
                    lines.append(f"![{chart_name}]({chart})")
                    lines.append("")

            lines.append("---")
            lines.append(f"*{labels['generated']}*")

            with open(filepath, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))

            self.logger.info(f"Markdown saved: {filepath}")
            self._save_version_entry(log_filepath, version, filename, author)
            return filepath

        except Exception as e:
            self.logger.error(f"Markdown generation failed: {e}")
            raise ExportError(f"Markdown generation failed: {e}")

    # ─── Helpers ─────────────────────────────────────────────────

    def _parse_sections_from_text(self, text: str) -> dict:
        """
        Parses the concatenated export text back into named sections.
        Looks for ## headings and maps them to known keys.
        """
        result = {
            "summary": "",
            "test_analysis": "",
            "test_analysis_summary": "",
            "risks_eval": "",
            "decision": "",
            "justification": "",
        }

        heading_map = {
            "podsumowanie": "summary",
            "summary": "summary",
            "analiza testow": "test_analysis",
            "analiza testów": "test_analysis",
            "test analysis": "test_analysis",
            "podsumowanie analizy": "test_analysis_summary",
            "test analysis summary": "test_analysis_summary",
            "ocena ryzyk": "risks_eval",
            "risk evaluation": "risks_eval",
            "decyzja": "decision",
            "decision": "decision",
            "uzasadnienie": "justification",
            "justification": "justification",
        }

        current_key = None
        current_lines = []

        for line in text.split("\n"):
            heading_match = re.match(r"^##\s+(.+)$", line.strip())
            if heading_match:
                if current_key:
                    result[current_key] = "\n".join(current_lines).strip()
                    current_lines = []

                raw_heading = heading_match.group(1).strip()
                # Handle "Decyzja: GO" style headings
                clean_heading = re.sub(r":.*$", "", raw_heading).strip().lower()
                current_key = heading_map.get(clean_heading)

                # Extract decision value from heading like "## Decyzja: GO"
                if clean_heading in ("decyzja", "decision") and ":" in raw_heading:
                    decision_val = raw_heading.split(":", 1)[1].strip()
                    result["decision"] = decision_val
            else:
                if current_key:
                    current_lines.append(line)

        if current_key and current_lines:
            result[current_key] = "\n".join(current_lines).strip()

        return result


class _StyledPDF(FPDF):
    """Custom FPDF subclass with branded headers and footers."""

    def __init__(self, labels, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.labels = labels
        self.default_font = "Helvetica"

    def header(self):
        if self.page_no() > 1:
            self.set_font(self.default_font, "", 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 8, self.labels["confidential"], align="C", ln=True)
            self.set_draw_color(227, 0, 15)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

    def footer(self):
        self.set_y(-20)
        self.set_font(self.default_font, "", 8)
        self.set_text_color(150, 150, 150)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.cell(
            0,
            8,
            f'{self.labels["generated"]}  |  '
            f'{self.labels["page"]} {self.page_no()}/{{nb}}',
            align="C",
        )
