# ============================================================
# FILE: .\backend\src\services\storage.py
# ============================================================

import os
import json
import uuid
from datetime import datetime
from typing import Optional

from src.core.config import Config
from src.core.logger import get_logger


class StorageManager:
    """Manages filesystem-based storage for projects, chats, and cached reports."""

    def __init__(self):
        self.logger = get_logger(self.__class__.__name__)
        self.projects_dir = Config.PROJECTS_PATH
        self.chats_dir = Config.CHATS_PATH

        os.makedirs(self.projects_dir, exist_ok=True)
        os.makedirs(self.chats_dir, exist_ok=True)

    @staticmethod
    def generate_id(prefix: str = "c") -> str:
        """
        Generates a unique ID with a given prefix (default "c" for chat, "p" for project).
        Example: p-4f8a9b21c3, c-9d8e7f6a5b
        """
        return f"{prefix}-{uuid.uuid4().hex[:12]}"

    # ==========================================
    # PROJECT MANAGEMENT (p-xxxxxx)
    # ==========================================
    def get_project_dir(self, project_id: str) -> str:
        """Returns the root directory for a project, creating it if necessary."""
        path = os.path.join(self.projects_dir, project_id)
        os.makedirs(path, exist_ok=True)
        return path

    def get_project_uploads_dir(self, project_id: str) -> str:
        """Directory for global knowledge files of the project (read-only for chats)."""
        path = os.path.join(self.get_project_dir(project_id), "uploads")
        os.makedirs(path, exist_ok=True)
        return path

    def save_project_instructions(self, project_id: str, instructions: str):
        """Saves global instructions (system prompt) for the project."""
        path = os.path.join(self.get_project_dir(project_id), "instructions.txt")
        with open(path, "w", encoding="utf-8") as f:
            f.write(instructions)

    def load_project_instructions(self, project_id: str) -> str:
        """Loads project instructions (returns empty string if not found)."""
        path = os.path.join(self.get_project_dir(project_id), "instructions.txt")
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        return ""

    # ==========================================
    # CHAT MANAGEMENT (c-xxxxxx)
    # ==========================================
    def get_chat_dir(self, chat_id: str) -> str:
        """Returns the root directory for a chat, creating it if necessary."""
        path = os.path.join(self.chats_dir, chat_id)
        os.makedirs(path, exist_ok=True)
        return path

    def get_chat_uploads_dir(self, chat_id: str) -> str:
        """Directory for files uploaded directly from the chat window (e.g., CSV for analysis)."""
        path = os.path.join(self.get_chat_dir(chat_id), "uploads")
        os.makedirs(path, exist_ok=True)
        return path

    def get_chat_created_dir(self, chat_id: str) -> str:
        """Directory for files generated by AI in the given chat."""
        path = os.path.join(self.get_chat_dir(chat_id), "created")
        os.makedirs(path, exist_ok=True)
        return path

    def link_chat_to_project(self, chat_id: str, project_id: Optional[str]):
        """Saves chat metadata (which project it belongs to)."""
        meta_path = os.path.join(self.get_chat_dir(chat_id), "meta.json")
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump(
                {"project_id": project_id, "created_at": datetime.now().isoformat()}, f
            )

    def get_chat_project_id(self, chat_id: str) -> Optional[str]:
        """Returns the project ID for the given chat or None (if standalone)."""
        meta_path = os.path.join(self.get_chat_dir(chat_id), "meta.json")
        if os.path.exists(meta_path):
            with open(meta_path, "r", encoding="utf-8") as f:
                return json.load(f).get("project_id")
        return None

    # ==========================================
    # CHAT CACHE MANAGEMENT (draft JSON in chat folder)
    # ==========================================

    def get_chat_cache_dir(self, chat_id: str) -> str:
        """Directory for conversation history and other temporary chat data."""
        path = os.path.join(self.get_chat_dir(chat_id), "cache")
        os.makedirs(path, exist_ok=True)
        return path

    def load_chat_history(self, chat_id: str) -> list:
        """Loads the conversation history from history.json."""
        history_path = os.path.join(self.get_chat_cache_dir(chat_id), "history.json")
        if os.path.exists(history_path):
            try:
                with open(history_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as e:
                self.logger.error(f"Failed to load chat history for {chat_id}: {e}")
        return []

    def save_chat_history(self, chat_id: str, history: list):
        """Saves the conversation history to history.json."""
        history_path = os.path.join(self.get_chat_cache_dir(chat_id), "history.json")
        try:
            with open(history_path, "w", encoding="utf-8") as f:
                json.dump(history, f, ensure_ascii=False, indent=2)
        except Exception as e:
            self.logger.error(f"Failed to save chat history for {chat_id}: {e}")

    # ==========================================
    # GO-NOGO CACHE MANAGEMENT (draft JSON in chat folder)
    # ==========================================

    def save_to_cache(self, chat_id: str, structured_data: dict, parsed_test_data: str = ""):
        """Saves the structured draft JSON to the chat's created directory."""
        created_dir = self.get_chat_created_dir(chat_id)
        filepath = os.path.join(created_dir, "draft_cache.json")

        cache_payload = {
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "chat_id": chat_id,
            "data": structured_data,
            "parsed_test_data": parsed_test_data,
        }

    def get_latest_history(self, chat_id: str) -> Optional[dict]:
        """Reads the latest draft cache for a given chat."""
        filepath = os.path.join(self.get_chat_created_dir(chat_id), "draft_cache.json")
        if os.path.exists(filepath):
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    return json.load(f)
            except Exception as e:
                self.logger.error(f"Failed to read cache file {filepath}: {e}")
        return None

    def clear_cache(self, chat_id: str) -> bool:
        """Deletes the draft cache file for a given chat. Returns True if deleted."""
        filepath = os.path.join(self.get_chat_created_dir(chat_id), "draft_cache.json")
        if os.path.exists(filepath):
            os.remove(filepath)
            self.logger.info(f"Cache deleted for chat: {chat_id}")
            return True
        return False
